### ISSUE TITLE
make run error

### ISSUE THREAD

**Issue by MarvinMiao** [felixfung/InfoFlow#3]
Hi, thank you for your graceful project. I tried to run your example by using make run, but I encountered below errors:
Error: Cannot load main class from JAR file:/home/miaoluwen/projects/qihoo360/scala/InfoFlow/target/scala-2.11/infoflow_2.11-1.0.jar
Could you please help me figure out what's the error?

**Comment by felixfung** [comment]
Thank you for the bug. Can you please try on the latest commit on master?
