### ISSUE TITLE
[Question] Does it work for directed, weighted graph?

### ISSUE THREAD

**Issue by Ishitori** [felixfung/InfoFlow#8]
Hi there, 

Original Infomap algorithm works on directed, weighted graph. Does Infoflow supports directed weighted graphs as well?

Did you try your algorithm on large graphs (like a few hundred million nodes and a billion edges)? What are the performance results?

**Comment by felixfung** [comment]
Hi,

Yes InfoFlow, both the algorithm and this implementation, supports directed weighted graphs.

We have not yet performed computation on large graphs.
